language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_install:
  - mv .env.example .env
  - travis_retry composer self-update

install:
  - composer install

script:
  - php artisan key:generate
  - vendor/bin/phpunit
